# Generated by Django 4.1.2 on 2022-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_category_producto_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='producto',
            name='is_avaible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='content',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre producto'),
        ),
    ]
