# Generated by Django 4.1.2 on 2022-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_subtitle_producto_is_avaible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
