# Generated by Django 4.1.2 on 2022-12-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_name_category_category_name_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='slug',
            new_name='slug2',
        ),
    ]
